version: '3'

services:
  centos:
    build: docker/centos
    volumes:
      - gnupg_centos:/root/.gnupg
      - ./dist:/dist
      - ./in:/in

  debian:
    build: docker/debian
    volumes:
      - gnupg_debian:/root/.gnupg
      - ./dist:/dist
      - ./in:/in

volumes:
  gnupg_centos:
  gnupg_debian:
